{
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "kind": "Role",
  "metadata": {
    "name": "fleet-mind-role",
    "labels": {
      "app": "fleet-mind"
    }
  },
  "rules": [
    {
      "apiGroups": [
        ""
      ],
      "resources": [
        "pods",
        "services"
      ],
      "verbs": [
        "get",
        "list",
        "watch"
      ]
    }
  ]
}