# Fleet-Mind Global Deployment Configuration
# Multi-region, multi-cloud deployment with compliance and localization

global:
  application:
    name: fleet-mind
    version: "0.1.0"
    environment: production
    
  # Global load balancer configuration
  load_balancer:
    provider: cloudflare  # cloudflare, aws-global-accelerator, azure-traffic-manager
    dns_name: fleet-mind.com
    health_check:
      path: /health
      interval: 30s
      timeout: 5s
      unhealthy_threshold: 3
    
  # Content Delivery Network
  cdn:
    provider: cloudflare
    cache_policy:
      static_assets: 1y
      api_responses: 5m
      websocket: no-cache
    compression: br,gzip
    
  # Security settings
  security:
    tls_version: "1.3"
    hsts_max_age: 31536000
    csp_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    rate_limiting:
      global: 1000/minute
      per_user: 100/minute
    
  # Data compliance
  compliance:
    gdpr_enabled: true
    ccpa_enabled: true
    data_retention_default: 365  # days
    audit_logging: true
    encryption_at_rest: true
    encryption_in_transit: true

# Regional deployments
regions:
  # Europe - GDPR compliance required
  europe:
    regions: [eu-west-1, eu-central-1, eu-north-1]
    primary_region: eu-west-1
    
    compliance:
      framework: GDPR
      data_residency: required
      consent_management: strict
      right_to_be_forgotten: true
      data_protection_officer: 
        name: "European DPO"
        email: "dpo-eu@fleet-mind.com"
      
    localization:
      languages: [en, de, fr, es, it, nl]
      timezone: Europe/London
      currency: EUR
      distance_unit: meters
      
    kubernetes:
      cluster_name: fleet-mind-eu
      node_pools:
        - name: coordinator
          instance_type: n1-standard-4
          min_nodes: 3
          max_nodes: 20
          zones: [eu-west-1a, eu-west-1b, eu-west-1c]
        - name: monitoring
          instance_type: n1-standard-2
          min_nodes: 1
          max_nodes: 3
          
    storage:
      encryption: AES-256
      backup_retention: 7y  # GDPR compliance
      backup_region: eu-central-1
      
  # North America - CCPA/SOC2 compliance
  north_america:
    regions: [us-east-1, us-west-2, ca-central-1]
    primary_region: us-east-1
    
    compliance:
      framework: CCPA
      data_residency: optional
      consent_management: opt-out
      right_to_be_forgotten: true
      
    localization:
      languages: [en, es, fr]
      timezone: America/New_York
      currency: USD
      distance_unit: feet
      
    kubernetes:
      cluster_name: fleet-mind-na
      node_pools:
        - name: coordinator
          instance_type: m5.xlarge
          min_nodes: 3
          max_nodes: 50
          zones: [us-east-1a, us-east-1b, us-east-1c]
          
  # Asia Pacific - PDPA/Privacy Act compliance
  asia_pacific:
    regions: [ap-southeast-1, ap-northeast-1, ap-south-1]
    primary_region: ap-southeast-1
    
    compliance:
      framework: PDPA
      data_residency: required
      consent_management: strict
      
    localization:
      languages: [en, ja, ko, zh-CN, zh-TW, hi]
      timezone: Asia/Singapore
      currency: USD
      distance_unit: meters
      
    kubernetes:
      cluster_name: fleet-mind-apac
      node_pools:
        - name: coordinator
          instance_type: c5.xlarge
          min_nodes: 2
          max_nodes: 30

# Multi-cloud configuration
cloud_providers:
  primary: gcp
  secondary: aws
  tertiary: azure
  
  gcp:
    project_id: fleet-mind-prod
    regions: [europe-west1, us-central1, asia-southeast1]
    services:
      kubernetes: gke
      storage: cloud-sql
      monitoring: cloud-monitoring
      
  aws:
    account_id: "123456789012"
    regions: [eu-west-1, us-east-1, ap-southeast-1]
    services:
      kubernetes: eks
      storage: rds
      monitoring: cloudwatch
      
  azure:
    subscription_id: "12345678-1234-1234-1234-123456789012"
    regions: [westeurope, eastus, southeastasia]
    services:
      kubernetes: aks
      storage: azure-database
      monitoring: azure-monitor

# Database configuration per region
databases:
  europe:
    type: postgresql
    version: "15"
    instance_class: db.r6g.xlarge
    storage: 500GB
    backup_retention: 35 days
    encryption: true
    multi_az: true
    
  north_america:
    type: postgresql
    version: "15"
    instance_class: db.r6g.2xlarge
    storage: 1TB
    backup_retention: 30 days
    encryption: true
    multi_az: true
    
  asia_pacific:
    type: postgresql
    version: "15"
    instance_class: db.r6g.large
    storage: 250GB
    backup_retention: 30 days
    encryption: true
    multi_az: true

# Monitoring and observability
monitoring:
  global_dashboards: true
  alerting:
    channels:
      - type: slack
        webhook: ${SLACK_WEBHOOK_URL}
      - type: pagerduty
        integration_key: ${PAGERDUTY_INTEGRATION_KEY}
      - type: email
        recipients: ["ops@fleet-mind.com"]
        
  metrics:
    retention: 90d
    high_cardinality_retention: 7d
    
  logs:
    retention: 30d
    compliance_logs_retention: 7y
    
  traces:
    sampling_rate: 0.1
    retention: 7d

# Disaster recovery
disaster_recovery:
  rpo: 1h  # Recovery Point Objective
  rto: 4h  # Recovery Time Objective
  
  backup_strategy:
    frequency: 4h
    retention: 30d
    cross_region: true
    
  failover:
    automatic: true
    health_check_failures: 3
    failover_time: 5m

# Cost optimization
cost_optimization:
  auto_scaling:
    enabled: true
    scale_down_delay: 10m
    scale_up_delay: 2m
    
  spot_instances:
    enabled: true
    percentage: 30
    
  scheduled_scaling:
    enabled: true
    business_hours: "08:00-18:00"
    timezone_aware: true

# CI/CD configuration
cicd:
  strategy: blue-green
  
  environments:
    - name: staging
      auto_deploy: true
      approval_required: false
      
    - name: production
      auto_deploy: false
      approval_required: true
      approvers: ["ops-team", "security-team"]
      
  deployment_windows:
    europe: "02:00-04:00 UTC"
    north_america: "08:00-10:00 UTC"
    asia_pacific: "14:00-16:00 UTC"
    
  testing:
    unit_tests: required
    integration_tests: required
    security_scans: required
    performance_tests: required
    compliance_checks: required

# Feature flags for global rollout
feature_flags:
  gdpr_consent_banner:
    enabled: true
    regions: [europe]
    
  ccpa_opt_out:
    enabled: true
    regions: [north_america]
    
  advanced_analytics:
    enabled: true
    percentage: 10
    
  websocket_compression:
    enabled: true
    regions: [asia_pacific]  # High latency regions first
    
  machine_learning_features:
    enabled: false
    canary_percentage: 5

# API Gateway configuration
api_gateway:
  rate_limiting:
    anonymous: 100/minute
    authenticated: 1000/minute
    premium: 10000/minute
    
  authentication:
    methods: [jwt, oauth2, api_key]
    session_timeout: 3600
    
  versioning:
    strategy: url_path  # /v1/, /v2/
    deprecation_notice: 90d
    
  caching:
    ttl: 300s
    vary_by: [user_id, region, language]

# Compliance automation
compliance_automation:
  data_retention_cleanup:
    schedule: "0 2 * * *"  # Daily at 2 AM
    dry_run: false
    
  gdpr_reports:
    schedule: "0 0 1 * *"  # Monthly
    recipients: ["dpo@fleet-mind.com"]
    
  security_scans:
    schedule: "0 4 * * 1"  # Weekly on Monday
    tools: [trivy, snyk, clair]
    
  audit_log_archival:
    schedule: "0 1 * * 0"  # Weekly on Sunday
    retention: 7y
    
  consent_renewal_reminders:
    schedule: "0 12 * * *"  # Daily at noon
    advance_notice: 30d

# Localization automation
localization:
  translation_updates:
    schedule: "0 6 * * 1"  # Weekly on Monday
    source: crowdin
    auto_merge: false
    
  currency_rates:
    schedule: "0 9 * * *"  # Daily at 9 AM
    provider: exchangerate-api
    
  timezone_updates:
    schedule: "0 3 1 */3 *"  # Quarterly
    source: iana

# Emergency procedures
emergency:
  incident_response:
    escalation_matrix:
      p1: 15m
      p2: 1h
      p3: 4h
      p4: 24h
      
  data_breach_response:
    internal_notification: 1h
    authority_notification: 72h
    user_notification: 72h
    forensics_team: ["security@fleet-mind.com"]
    
  service_degradation:
    auto_mitigation: true
    traffic_shedding: 50%
    graceful_degradation: true